### ISSUE TITLE
Fatal Error on Mac OS High Sierra

### ISSUE THREAD

**Issue by AaronEast** [thbishop/mmfa#8]
Hello,
After upgrading to High Sierra mmfa is no longer working.

```failed MSpanList_Insert 0x333000 0x20ac2a95d9ef5 0x0
fatal error: MSpanList_Insert

runtime stack:
<empty>
```

I've uninstalled and re-installed via homebrew and by hand through github.

**Comment by jperez-dx** [comment]
Same problem here.

**Comment by thbishop** [comment]
@AaronEast @jperez-dx Sorry for the delay. I've released [0.3.1](https://github.com/thbishop/mmfa/releases/tag/0.3.1) which should address the issue. Give it a whirl and let me know if it works for you.

**Comment by capen** [comment]
@thbishop worked for me! 👍

**Comment by thbishop** [comment]
Closing. If you hit any issues, feel free to report back. Thanks.

**Comment by AaronEast** [comment]
@thbishop I'm finally getting back to this, sorry for the delay.  It's working now, thanks.
